# Generated by Django 4.2.2 on 2023-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_liked',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to='network.post'),
        ),
    ]
