# Generated by Django 4.2.2 on 2023-07-06 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_liked',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
